name: 'Download file from URL and cache it in GitHub Actions'
description: 'This GitHub Action downloads a file from a specified URL and caches it to avoid repeated downloads on subsequent runs.'
branding:
  icon: 'download'
  color: 'green'
inputs:
  url:
    description: 'URL of the file to download'
    required: true
  destination:
    description: 'Destination directory to save the downloaded file'
    required: false
    default: 'temp'
  filename:
    description: 'Set the name of the downloaded file'
    required: false
    default: ''
outputs:
  filename:
    description: 'Name of the downloaded file'
    value: ${{ steps.get-filename.outputs.filename }}
  filepath:
    description: 'Path to the downloaded file'
    value: ${{ steps.set-output.outputs.filepath }}
runs:
  using: 'composite'
  steps:
    - name: Get file name
      id: get-filename
      shell: bash
      run: |
        if [ -n "${{ inputs.filename }}" ]; then
          echo "filename=${{ inputs.filename }}" >> $GITHUB_OUTPUT
        else
          echo "filename=$(basename ${{ inputs.url }})" >> $GITHUB_OUTPUT
        fi
    - name: Set output path
      id: set-output
      shell: bash
      env:
        mercury233_action_cache_download_file_filename: ${{ steps.get-filename.outputs.filename }}
      run: |
        echo "filepath=${{ inputs.destination }}/${{ env.mercury233_action_cache_download_file_filename }}" >> $GITHUB_OUTPUT
    - name: Check cache
      id: cache
      uses: actions/cache/restore@v4
      env:
        mercury233_action_cache_download_file_filename: ${{ steps.get-filename.outputs.filename }}
      with:
        key: ${{ inputs.url }}
        path: ${{ inputs.destination }}/${{ env.mercury233_action_cache_download_file_filename }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Download file
      shell: bash
      env:
        mercury233_action_cache_download_file_filename: ${{ steps.get-filename.outputs.filename }}
      run: |
        mkdir -p ${{ inputs.destination }}
        curl --retry 5 --connect-timeout 30 --location \
          -o ${{ inputs.destination }}/${{ env.mercury233_action_cache_download_file_filename }} \
          ${{ inputs.url }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Save cache
      uses: actions/cache/save@v4
      env:
        mercury233_action_cache_download_file_filename: ${{ steps.get-filename.outputs.filename }}
      with:
        key: ${{ inputs.url }}
        path: ${{ inputs.destination }}/${{ env.mercury233_action_cache_download_file_filename }}
