name: 'Download file from URL and cache it in GitHub Actions'
description: 'Download file from URL and cache it in GitHub Actions, to avoid downloading it every time'
inputs:
  url:
    description: 'URL of the file to download'
    required: true
  destination:
    description: 'Destination directory to save the downloaded file'
    required: false
    default: 'temp'
  filename:
    description: 'Set the name of the downloaded file'
    required: false
    default: ''
outputs:
  file-path:
    description: 'Path to the downloaded file'
runs:
  using: "composite"
  steps:
    - name: Set output name
      id: set-output
      shell: bash
      run: |
        if [ -n "${{ inputs.filename }}" ]; then
          echo "filename=${{ inputs.filename }}" >> $GITHUB_ENV
        else
          echo "filename=$(basename ${{ inputs.url }})" >> $GITHUB_ENV
        fi
        echo "file-path=${{ inputs.destination }}/${{ env.filename }}" >> $GITHUB_OUTPUT
    - name: Check cache
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{ inputs.url }}
        path: ${{ inputs.destination }}/${{ env.filename }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Download file
      shell: bash
      run: |
        mkdir -p ${{ inputs.destination }}
        curl --retry 5 --connect-timeout 30 --location `
          -o ${{ inputs.destination }}/${{ env.filename }} `
          ${{ inputs.url }}
